### PR TITLE
-

### PR DESCRIPTION
**Pull request by huyz-git**

### CODE REVIEW

**Comment by huyz-git** [comment]
Also, clash doesn't support send DNS through proxy. So if a clash user wishes to send DNS through proxy, it needs to use tools like `dnsproxy` which sets a local DNS server and send DNS to remote which will go through (transparent) proxy.
The `hijack_dns_ignore` config will make sure that the traffic send by `dnsproxy` can go through (transparent) proxy without being hijacked into clash's DNS port.

**Comment by huyz-git** [comment]
> Also, clash doesn't support send DNS through proxy. So if a clash user wishes to send DNS through proxy, it needs to use tools like `dnsproxy` which sets a local DNS server and send DNS to remote which will go through (transparent) proxy.
> The `hijack_dns_ignore` config will make sure that the traffic send by `dnsproxy` can go through (transparent) proxy without being hijacked into clash's DNS port.

Sometimes, the `dnsproxy` client may have multiple remote DNS, so it's more convenient to set up a cgroup in which DNS will not be hijacked.

**Comment by huyz-git** [comment]
https://github.com/springzfx/cgproxy/blob/aaa628a76b2911018fc93b2e3276c177e85e0861/cgroup-tproxy.sh#L179-L180

Perhaps these two socket rules should be only applied to TCP protocol.
If it applied to UDP protocol, then incoming UDP packet sometimes cannot received when using some TPROXY tools like `ipt2socks`, which makes UDP NAT type at most NAT3.

**Comment by yangon99** [comment]
I can't build this pr correctly...
```
CMake Error: File /src/cgproxy/cgdnsproxy.cmake does not exist.
CMake Error at CMakeLists.txt:31 (configure_file):
  configure_file Problem configuring file
```

**Pull request closed without merging**
