### PR TITLE
Fix Packaging

### PR DESCRIPTION
**Pull request by karuboniru**
Current Package seems to be broken

### CODE REVIEW

**Comment by karuboniru** [comment]
created on my mobile, didn't test, but should work

**Comment by springzfx** [comment]
Thank you for this report. I have updated release. The origin problem comes from build tool `cmake`. 
cmake's behavior is not consistent with their document.
> DESTINATION
 Specify the directory on disk to which a file will be installed. Arguments can be relative or absolute paths.
 **If a relative path is given it is interpreted relative to the value of the CMAKE_INSTALL_PREFIX variable.** The prefix can     be relocated at install time using the DESTDIR mechanism explained in the CMAKE_INSTALL_PREFIX variable documentation.
 If an absolute path (with a leading slash or drive letter) is given it is used verbatim.
 As absolute paths are not supported by cpack installer generators, it is preferable to use relative paths throughout.

quote from https://cmake.org/cmake/help/latest/command/install.html

**Comment by karuboniru** [comment]
okay, if no longer needed, please close anyway.

**Comment by springzfx** [comment]
And their is no reason to set CMAKE_INSTALL_PREFIX directly. Whoever wants to install from source may like to set it manually. I close this now. Thank you again for this.

**Comment by springzfx** [comment]
a workaround https://github.com/springzfx/cgproxy/commit/5902a649262a5b6468a1f937f0526d06ca3aa1fe

**Pull request closed without merging**
